/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 *
 * @author Supri
 */
public class CustomerProfileView extends javax.swing.JFrame {

    /**
     * Creates new form CustomerProfileView
     */
    public CustomerProfileView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        schoolLabel = new javax.swing.JLabel();
        schoolComboBox = new javax.swing.JComboBox();
        profileViewSeparator = new javax.swing.JSeparator();
        manualFillPanel = new javax.swing.JPanel();
        primaryContactLabel = new javax.swing.JLabel();
        primaryContactTextField = new javax.swing.JTextField();
        primaryEmailLabel = new javax.swing.JLabel();
        materialContactLabel = new javax.swing.JLabel();
        materialContactTextField = new javax.swing.JTextField();
        materialEmailLabel = new javax.swing.JLabel();
        primaryEmailTextField = new javax.swing.JTextField();
        materialEmailTextField = new javax.swing.JTextField();
        autoFillPanel = new javax.swing.JPanel();
        countryLabel = new javax.swing.JLabel();
        countryTextField = new javax.swing.JTextField();
        stateLabel = new javax.swing.JLabel();
        stateTextField = new javax.swing.JTextField();
        cityLabel = new javax.swing.JLabel();
        cityTextField = new javax.swing.JTextField();
        postalCodeLabel = new javax.swing.JLabel();
        postalCodeTextField = new javax.swing.JTextField();
        addressLabel = new javax.swing.JLabel();
        addressTextField = new javax.swing.JTextField();
        phoneLabel = new javax.swing.JLabel();
        phoneTextField = new javax.swing.JTextField();
        faxLabel = new javax.swing.JLabel();
        faxTextField = new javax.swing.JTextField();
        nextButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(240, 240, 240));

        schoolLabel.setText("Select School:");

        schoolComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Select School>", "Point Grey Secondary School", "Britannia Secondary School", "Lord Byng Secondary School", "Sir Winston Churchill Secondary School", "Crofton House School", "David Thompson Secondary School", "Eric Hamber Secondary School", "Gladstone Secondary School", "John Oliver Secondary School", "King David High School", "Kitsilano Secondary School", "David Thompson Secondary School", "Little Flower Academy", "Magee Secondary School", "Notre Dame Regional Secondary School", "Prince of Wales Secondary School", "St. George's School", "St. John's School", "Sir Charles Tupper Secondary School", "Stratford Hall", "Templeton Secondary School\"", "University Hill Secondary School", "York House School", "West Point Grey Academy", "Windermere Secondary School" }));

        primaryContactLabel.setText("Primary Contact:");

        primaryContactTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        primaryEmailLabel.setText("Email:");

        materialContactLabel.setText("Material Contact:");

        materialContactTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        materialEmailLabel.setText("Email:");

        primaryEmailTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        materialEmailTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        org.jdesktop.layout.GroupLayout manualFillPanelLayout = new org.jdesktop.layout.GroupLayout(manualFillPanel);
        manualFillPanel.setLayout(manualFillPanelLayout);
        manualFillPanelLayout.setHorizontalGroup(
            manualFillPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(manualFillPanelLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(manualFillPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(manualFillPanelLayout.createSequentialGroup()
                        .add(primaryContactLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(primaryContactTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 150, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(manualFillPanelLayout.createSequentialGroup()
                        .add(materialContactLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(materialContactTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 150, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(34, 34, 34)
                .add(manualFillPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, primaryEmailLabel)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, materialEmailLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(manualFillPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(materialEmailTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .add(primaryEmailTextField))
                .addContainerGap())
        );

        manualFillPanelLayout.linkSize(new java.awt.Component[] {materialContactLabel, primaryContactLabel}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        manualFillPanelLayout.linkSize(new java.awt.Component[] {materialEmailLabel, primaryEmailLabel}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        manualFillPanelLayout.setVerticalGroup(
            manualFillPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(manualFillPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(manualFillPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(primaryContactLabel)
                    .add(primaryContactTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(primaryEmailLabel)
                    .add(primaryEmailTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(manualFillPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(materialContactLabel)
                    .add(materialContactTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(materialEmailLabel)
                    .add(materialEmailTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        countryLabel.setText("Country:");

        countryTextField.setEditable(false);
        countryTextField.setBackground(new java.awt.Color(222, 222, 222));
        countryTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        stateLabel.setText("State/Province:");

        stateTextField.setEditable(false);
        stateTextField.setBackground(new java.awt.Color(222, 222, 222));
        stateTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        cityLabel.setText("City:");

        cityTextField.setEditable(false);
        cityTextField.setBackground(new java.awt.Color(222, 222, 222));

        postalCodeLabel.setText("Postal Code:");

        postalCodeTextField.setEditable(false);
        postalCodeTextField.setBackground(new java.awt.Color(222, 222, 222));
        postalCodeTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        addressLabel.setText("Address:");

        addressTextField.setEditable(false);
        addressTextField.setBackground(new java.awt.Color(222, 222, 222));

        phoneLabel.setText("Phone:");

        phoneTextField.setEditable(false);
        phoneTextField.setBackground(new java.awt.Color(222, 222, 222));
        phoneTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        faxLabel.setText("Fax:");

        faxTextField.setEditable(false);
        faxTextField.setBackground(new java.awt.Color(222, 222, 222));
        faxTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        org.jdesktop.layout.GroupLayout autoFillPanelLayout = new org.jdesktop.layout.GroupLayout(autoFillPanel);
        autoFillPanel.setLayout(autoFillPanelLayout);
        autoFillPanelLayout.setHorizontalGroup(
            autoFillPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(autoFillPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(autoFillPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(autoFillPanelLayout.createSequentialGroup()
                        .add(cityLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(cityTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 150, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(postalCodeLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(postalCodeTextField))
                    .add(autoFillPanelLayout.createSequentialGroup()
                        .add(addressLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(addressTextField))
                    .add(autoFillPanelLayout.createSequentialGroup()
                        .add(autoFillPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(autoFillPanelLayout.createSequentialGroup()
                                .add(countryLabel)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(countryTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(autoFillPanelLayout.createSequentialGroup()
                                .add(stateLabel)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(stateTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 150, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(autoFillPanelLayout.createSequentialGroup()
                                .add(phoneLabel)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(phoneTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 150, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(18, 18, 18)
                                .add(faxLabel)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(faxTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 150, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .add(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        autoFillPanelLayout.setVerticalGroup(
            autoFillPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(autoFillPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(autoFillPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(countryLabel)
                    .add(countryTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(autoFillPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(stateLabel)
                    .add(stateTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(autoFillPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(cityLabel)
                    .add(cityTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(postalCodeLabel)
                    .add(postalCodeTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(autoFillPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(addressLabel)
                    .add(addressTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(autoFillPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(phoneLabel)
                    .add(phoneTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(faxLabel)
                    .add(faxTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        nextButton.setText("Next");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(profileViewSeparator)
                .addContainerGap())
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(29, 29, 29)
                        .add(schoolLabel)
                        .add(18, 18, 18)
                        .add(schoolComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 275, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(26, 169, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .add(0, 25, Short.MAX_VALUE)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(nextButton)
                            .add(manualFillPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .add(25, 25, 25))
            .add(layout.createSequentialGroup()
                .add(82, 82, 82)
                .add(autoFillPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(25, 25, 25)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(schoolComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(schoolLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(autoFillPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(profileViewSeparator, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(manualFillPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(nextButton)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public String getSchoolName(){
        return schoolComboBox.getSelectedItem().toString();
    }
    
    public String getPrimaryContact(){
        return primaryContactTextField.getText();
    }
    
    public String getPrimaryEmail(){
        return primaryEmailTextField.getText();
    }
    
    public String getMaterialContact(){
        return materialContactTextField.getText();
    }
    
    public String getMaterialEmail(){
        return materialEmailTextField.getText();
    }
    
    public void setCountry(String aCountry){
        countryTextField.setText(aCountry);
    }
    
    public void setState(String aState){
        stateTextField.setText(aState);
    }
    
    public void setCity(String aCity){
        cityTextField.setText(aCity);
    }
    
    public void setPostalCode(String aPostalCode){
        postalCodeTextField.setText(aPostalCode);
    }
    
    public void setAddress(String anAddress){
        addressTextField.setText(anAddress);
    }
    
    public void setPhone(String aPhoneNumber){
        phoneTextField.setText(aPhoneNumber);
    }
    
    public void setFax(String aFaxNumber){
        faxTextField.setText(aFaxNumber);
    }
       
    public void displayErrorMessage(String message) {
        JOptionPane.showMessageDialog(this, message);
    }
            
    public void addSchoolComboBoxListener(ActionListener listenSchoolComboBox){
        schoolComboBox.addActionListener(listenSchoolComboBox);
    }
    
    public void addNextButtonListener(ActionListener listenNextButton){
        nextButton.addActionListener(listenNextButton);
    }
    
    /*
    public void addShoolToComboBox(Set<String> schoolList){
        schoolComboBox.addItem(schoolList);
    }
    */
    
    public void primaryEmailError() {
        primaryEmailTextField.setText(null);
        primaryEmailLabel.setForeground(Color.red);
    }
    
    public void primaryEmailResetSetting() {
        primaryEmailLabel.setForeground(Color.black);
    }
    
    public void materialEmailError() {
        materialEmailTextField.setText(null);
        materialEmailLabel.setForeground(Color.red);
    }
    
    
    public void materialEmailResetSetting() {
        materialEmailLabel.setForeground(Color.black);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextField addressTextField;
    private javax.swing.JPanel autoFillPanel;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JTextField cityTextField;
    private javax.swing.JLabel countryLabel;
    private javax.swing.JTextField countryTextField;
    private javax.swing.JLabel faxLabel;
    private javax.swing.JTextField faxTextField;
    private javax.swing.JPanel manualFillPanel;
    private javax.swing.JLabel materialContactLabel;
    private javax.swing.JTextField materialContactTextField;
    private javax.swing.JLabel materialEmailLabel;
    private javax.swing.JTextField materialEmailTextField;
    private javax.swing.JButton nextButton;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JTextField phoneTextField;
    private javax.swing.JLabel postalCodeLabel;
    private javax.swing.JTextField postalCodeTextField;
    private javax.swing.JLabel primaryContactLabel;
    private javax.swing.JTextField primaryContactTextField;
    private javax.swing.JLabel primaryEmailLabel;
    private javax.swing.JTextField primaryEmailTextField;
    private javax.swing.JSeparator profileViewSeparator;
    private javax.swing.JComboBox schoolComboBox;
    private javax.swing.JLabel schoolLabel;
    private javax.swing.JLabel stateLabel;
    private javax.swing.JTextField stateTextField;
    // End of variables declaration//GEN-END:variables

}
