/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Supri
 */
public class CustomerProfileView extends javax.swing.JFrame {

    /**
     * Creates new form CustomerProfileView
     */
    public CustomerProfileView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        schoolLabel = new javax.swing.JLabel();
        schoolCombobox = new javax.swing.JComboBox();
        profileViewSeparator = new javax.swing.JSeparator();
        manualFillPanel = new javax.swing.JPanel();
        primaryContactLabel = new javax.swing.JLabel();
        primaryContactTextField = new javax.swing.JTextField();
        primaryEmailLabel = new javax.swing.JLabel();
        materialContactLabel = new javax.swing.JLabel();
        materialContactTextField = new javax.swing.JTextField();
        materialEmailLabel = new javax.swing.JLabel();
        primaryEmailFormattedField = new javax.swing.JFormattedTextField();
        materialEmailFormattedField = new javax.swing.JFormattedTextField();
        autoFillPanel = new javax.swing.JPanel();
        countryLabel = new javax.swing.JLabel();
        countryTextField = new javax.swing.JTextField();
        stateLabel = new javax.swing.JLabel();
        stateTextField = new javax.swing.JTextField();
        cityLabel = new javax.swing.JLabel();
        cityTextField = new javax.swing.JTextField();
        postalCodeLabel = new javax.swing.JLabel();
        postalCodeTextField = new javax.swing.JTextField();
        addressLabel = new javax.swing.JLabel();
        addressTextField = new javax.swing.JTextField();
        phoneLabel = new javax.swing.JLabel();
        phoneTextField = new javax.swing.JTextField();
        faxLabel = new javax.swing.JLabel();
        faxTextField = new javax.swing.JTextField();
        nextButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(240, 240, 240));

        schoolLabel.setText("Select School:");

        schoolCombobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        schoolCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schoolComboboxActionPerformed(evt);
            }
        });

        manualFillPanel.setBackground(new java.awt.Color(240, 240, 240));

        primaryContactLabel.setText("Primary Contact:");

        primaryContactTextField.setForeground(new java.awt.Color(200, 200, 200));
        primaryContactTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        primaryContactTextField.setText("Enter Name");

        primaryEmailLabel.setText("Email:");

        materialContactLabel.setText("Material Contact:");

        materialContactTextField.setForeground(new java.awt.Color(200, 200, 200));
        materialContactTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        materialContactTextField.setText("Enter Name");

        materialEmailLabel.setText("Email:");

        primaryEmailFormattedField.setForeground(new java.awt.Color(200, 200, 200));
        primaryEmailFormattedField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        primaryEmailFormattedField.setText("Enter email");

        materialEmailFormattedField.setForeground(new java.awt.Color(200, 200, 200));
        materialEmailFormattedField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        materialEmailFormattedField.setText("Enter email");

        org.jdesktop.layout.GroupLayout manualFillPanelLayout = new org.jdesktop.layout.GroupLayout(manualFillPanel);
        manualFillPanel.setLayout(manualFillPanelLayout);
        manualFillPanelLayout.setHorizontalGroup(
            manualFillPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(manualFillPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(manualFillPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(manualFillPanelLayout.createSequentialGroup()
                        .add(primaryContactLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(primaryContactTextField))
                    .add(manualFillPanelLayout.createSequentialGroup()
                        .add(materialContactLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(materialContactTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 112, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(18, 18, 18)
                .add(manualFillPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(manualFillPanelLayout.createSequentialGroup()
                        .add(primaryEmailLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(primaryEmailFormattedField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 131, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(manualFillPanelLayout.createSequentialGroup()
                        .add(materialEmailLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(materialEmailFormattedField)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        manualFillPanelLayout.linkSize(new java.awt.Component[] {materialContactLabel, primaryContactLabel}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        manualFillPanelLayout.linkSize(new java.awt.Component[] {materialEmailLabel, primaryEmailLabel}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        manualFillPanelLayout.setVerticalGroup(
            manualFillPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(manualFillPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(manualFillPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(primaryContactLabel)
                    .add(primaryContactTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(primaryEmailLabel)
                    .add(primaryEmailFormattedField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(manualFillPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(materialContactLabel)
                    .add(materialContactTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(materialEmailLabel)
                    .add(materialEmailFormattedField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        countryLabel.setText("Country:");

        countryTextField.setEditable(false);
        countryTextField.setBackground(new java.awt.Color(222, 222, 222));

        stateLabel.setText("State/Province:");

        stateTextField.setEditable(false);
        stateTextField.setBackground(new java.awt.Color(222, 222, 222));

        cityLabel.setText("City:");

        cityTextField.setEditable(false);
        cityTextField.setBackground(new java.awt.Color(222, 222, 222));

        postalCodeLabel.setText("Postal Code:");

        postalCodeTextField.setEditable(false);
        postalCodeTextField.setBackground(new java.awt.Color(222, 222, 222));

        addressLabel.setText("Address:");

        addressTextField.setEditable(false);
        addressTextField.setBackground(new java.awt.Color(222, 222, 222));

        phoneLabel.setText("Phone:");

        phoneTextField.setEditable(false);
        phoneTextField.setBackground(new java.awt.Color(222, 222, 222));

        faxLabel.setText("Fax:");

        faxTextField.setEditable(false);
        faxTextField.setBackground(new java.awt.Color(222, 222, 222));

        org.jdesktop.layout.GroupLayout autoFillPanelLayout = new org.jdesktop.layout.GroupLayout(autoFillPanel);
        autoFillPanel.setLayout(autoFillPanelLayout);
        autoFillPanelLayout.setHorizontalGroup(
            autoFillPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(autoFillPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(autoFillPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(autoFillPanelLayout.createSequentialGroup()
                        .add(autoFillPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(autoFillPanelLayout.createSequentialGroup()
                                .add(countryLabel)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(countryTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(autoFillPanelLayout.createSequentialGroup()
                                .add(stateLabel)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(stateTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 150, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .add(0, 0, Short.MAX_VALUE))
                    .add(autoFillPanelLayout.createSequentialGroup()
                        .add(cityLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(cityTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 150, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(postalCodeLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(postalCodeTextField))
                    .add(autoFillPanelLayout.createSequentialGroup()
                        .add(addressLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(addressTextField))
                    .add(autoFillPanelLayout.createSequentialGroup()
                        .add(phoneLabel)
                        .add(18, 18, 18)
                        .add(phoneTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 111, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 62, Short.MAX_VALUE)
                        .add(faxLabel)
                        .add(18, 18, 18)
                        .add(faxTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 111, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        autoFillPanelLayout.setVerticalGroup(
            autoFillPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(autoFillPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(autoFillPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(countryLabel)
                    .add(countryTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(autoFillPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(stateLabel)
                    .add(stateTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(autoFillPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(cityLabel)
                    .add(cityTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(postalCodeLabel)
                    .add(postalCodeTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(autoFillPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(addressLabel)
                    .add(addressTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(autoFillPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(autoFillPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(phoneLabel)
                        .add(phoneTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(autoFillPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(faxTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(faxLabel)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        nextButton.setText("Next");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(profileViewSeparator)
                .addContainerGap())
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(nextButton))
                    .add(layout.createSequentialGroup()
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(manualFillPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                                .add(25, 25, 25)
                                .add(schoolLabel)
                                .add(18, 18, 18)
                                .add(schoolCombobox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 150, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                                .add(31, 31, 31)
                                .add(autoFillPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .add(0, 0, Short.MAX_VALUE)))
                .add(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(25, 25, 25)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(schoolCombobox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(schoolLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(autoFillPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(profileViewSeparator, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(manualFillPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(nextButton)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void schoolComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schoolComboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_schoolComboboxActionPerformed

    public String getPrimaryContact(){
        return primaryContactTextField.getText();
    }
    
    public String getPrimaryEmail(){
        return primaryEmailFormattedField.getText();
    }
    
    public String getMaterialContact(){
        return materialContactTextField.getText();
    }
    
    public String getMaterialEmail(){
        return materialEmailFormattedField.getText();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerProfileView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerProfileView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerProfileView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerProfileView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerProfileView().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextField addressTextField;
    private javax.swing.JPanel autoFillPanel;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JTextField cityTextField;
    private javax.swing.JLabel countryLabel;
    private javax.swing.JTextField countryTextField;
    private javax.swing.JLabel faxLabel;
    private javax.swing.JTextField faxTextField;
    private javax.swing.JPanel manualFillPanel;
    private javax.swing.JLabel materialContactLabel;
    private javax.swing.JTextField materialContactTextField;
    private javax.swing.JFormattedTextField materialEmailFormattedField;
    private javax.swing.JLabel materialEmailLabel;
    private javax.swing.JButton nextButton;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JTextField phoneTextField;
    private javax.swing.JLabel postalCodeLabel;
    private javax.swing.JTextField postalCodeTextField;
    private javax.swing.JLabel primaryContactLabel;
    private javax.swing.JTextField primaryContactTextField;
    private javax.swing.JFormattedTextField primaryEmailFormattedField;
    private javax.swing.JLabel primaryEmailLabel;
    private javax.swing.JSeparator profileViewSeparator;
    private javax.swing.JComboBox schoolCombobox;
    private javax.swing.JLabel schoolLabel;
    private javax.swing.JLabel stateLabel;
    private javax.swing.JTextField stateTextField;
    // End of variables declaration//GEN-END:variables
}
